### ISSUE TITLE
Can't install plugin: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ElieSauveterre** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#581]
Since yesterday (September 18) the plugin install doesn't work, without having changed anything. I have a build pipeline with Gitlab CI. It's using a Docker image with all the dependencies preinstalled (npm, cordova, ionic...). A build that was working 2 days ago, is now failing.

My console output:

`ionic cordova plugin add branch-cordova-sdk`
 `cordova plugin add branch-cordova-sdk`

`You have been opted out of telemetry. To change this, run: cordova telemetry on.`
`Plugin "branch-cordova-sdk" already installed on android.`
`Adding branch-cordova-sdk to package.json`
`Cannot read property '0' of undefined`
`[ERROR] An error occurred while running subprocess cordova.`
 `cordova plugin add branch-cordova-sdk exited with exit code 1.`
 `Re-running this command with the --verbose flag may provide more information.`

I'm using:
- node 8.15.0
- npm 6.7.0
- ionic 5.2.3
- cordova 8.1.2

I also tried with
- node 8.15.0
- npm 6.11.3
- ionic 5.3.0
- cordova 9.0.0

**Comment by ronkot** [comment]
I encountered the same problem. A week ago build was working but now `cordova platform add android` fails. Here's the error when running the command in verbose mode:

```Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at getManifest (/Users/me/projects/project/project-cordova-deploy/project-web/plugins/branch-cordova-sdk/src/scripts/android/updateAndroidManifest.js:75:36)
    at Object.writePreferences (/Users/me/projects/project/project-cordova-deploy/project-web/plugins/branch-cordova-sdk/src/scripts/android/updateAndroidManifest.js:15:22)
    at platforms.forEach.platform (/Users/me/projects/project/project-cordova-deploy/project-web/plugins/branch-cordova-sdk/src/scripts/hooks/afterPrepare.js:20:25)
    at Array.forEach (<anonymous>)
    at run (/Users/me/projects/project/project-cordova-deploy/project-web/plugins/branch-cordova-sdk/src/scripts/hooks/afterPrepare.js:18:15)
    at runScriptViaModuleLoader (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:196:18)
    at runScript (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:172:16)
    at /Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:140:20
    at _fulfilled (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/q/q.js:854:54)
    at /Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/cordova/node_modules/q/q.js:883:30```

**Comment by psnfrench** [comment]
This seems to be an issue with `cordova-android 8.1.0`. It doesn't seem to add the same records to `AndroidManifest.xml` that is used to and hence the branch-cordova-sdk cannot get the `uses-sdk` tag and determine the target sdk version.

When I specify the android version explicitly to an earlier version the problem no longer occurs i.e:

`ionic cordova platform add android@8.0.0`

**Comment by yadhukrishnas** [comment]
I encountered the same error. 4 days back every thing is working  but now ionic cordova platform add android fails .

**Comment by deliverymanager** [comment]
+1

**Comment by deliverymanager** [comment]
Here is the error:

<img width="1196" alt="Screenshot 2019-09-25 14 52 48" src="https://user-images.githubusercontent.com/4013348/65598512-495d6980-dfa4-11e9-8292-790df1d1d10e.png">

**Comment by noahcooper** [comment]
Any update from the Branch team?

**Comment by undersieg** [comment]
`uses-sdk` should no longer be declared in the manifest, please check [https://github.com/apache/cordova-android/issues/629](https://github.com/apache/cordova-android/issues/629)

**Comment by Leo1305Pineda** [comment]
In the version npm i branch-cordova-sdk@^4.0.0 be omit the requese targetVersionSdk use this version

**Comment by noahcooper** [comment]
> In the version npm i branch-cordova-sdk@^4.0.0 be omit the requese targetVersionSdk use this version

Just keep in mind that the tradeoff is that as of version 4.0.0, you have to manually build from Xcode. https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/601

**Comment by epetre** [comment]
> Any update from the Branch team?

Any news?

**Comment by tryhardest** [comment]
Is this being worked on?

**Comment by noahcooper** [comment]
> Is this being worked on?

This is fixed in version 4.0.0, and now works properly with cordova-android 8.1.0. The problem is that version 4.0.0 introduces a change for iOS that makes it so that you cannot build from the command line and now have to build directly in Xcode. Super annoying, as it means that you're forced to choose to use a version that works with Android, or use a different version that works with iOS.

**Comment by Mapiac** [comment]
@noahcooper did you find a work around? Or @adrianyg7 and way to get around this iOS bug on 4.0.0?

**Comment by codinronan** [comment]
@noahcooper @Mapiac you should be able to use 3.2.1 which is now published, which fixes the issue for cordova-android in the branch plugin's 3.x line.

If you're using cordova 8/9 and build using xcode, you'll want to use the 4.0 line. We know about the inability to build on the command line, it's an issue the iOS team will take on at some point but requires significant reorganization of the native library so will take some time.

**Comment by codinronan** [comment]
@echo-branch would it make sense to close this issue now?

**Comment by noahcooper** [comment]
Version 3.2.1 works for me.
