### ISSUE TITLE
Branch.h - iOS build doesn't work

### ISSUE THREAD

**Issue by adrenaline15** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#642]

**Comment by felipeclopes** [comment]
I'm facing the same issue, and it only happens running the build command on terminal. It works properly on xCode.

**Project dependencies:**
```
$ ionic info

Ionic:

   Ionic CLI                     : 6.1.0 (/Users/myUser/.nvm/versions/node/v12.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.0
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.5, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)

Utility:

   cordova-res : 0.11.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/usr/local/share/android-sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.13.0 (/Users/myUser/.nvm/versions/node/v12.13.0/bin/node)
   npm               : 6.12.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.4 Build version 11E146
```

**Installed plugins:**
```
> cordova plugin ls
branch-cordova-sdk 4.1.2 "branch-cordova-sdk"
cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.3.0 "Facebook Connect"
cordova-plugin-firebasex 8.1.1 "Google Firebase Plugin"
cordova-plugin-health 1.1.3 "Cordova Health"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic 5.4.5 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-purchases 1.0.5 "Purchases"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**Build output:**
```
ionic cordova build ios
```
```
In file included from /Users/myUser/Projects/myProject/ionic4/platforms/ios/myProject/Plugins/branch-cordova-sdk/BranchSDK.m:1:
/Users/myUser/Projects/myProject/ionic4/platforms/ios/myProject/Plugins/branch-cordova-sdk/BranchSDK.h:4:9: fatal error: 'Branch.h' file not found
#import "Branch.h"
        ^~~~~~~~~~
1 error generated.

...

warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'Branch' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/myUser/Library/Developer/Xcode/DerivedData/myProject-aoynxopuapcojndwtqkcbsfscfqw/Build/Intermediates.noindex/ArchiveIntermediates/myProject/IntermediateBuildFilesPath/myProject.build/Debug-iphoneos/myProject.build/Objects-normal/arm64/BranchSDK.o /Users/myUser/Projects/myProject/ionic4/platforms/ios/myProject/Plugins/branch-cordova-sdk/BranchSDK.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Command finished with error code 65: xcodebuild -workspace,myProject.xcworkspace,-scheme,myProject,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,myProject.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/myUser/Projects/myProject/ionic4/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/myUser/Projects/myProject/ionic4/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/myUser/Projects/mighty/ionic4/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by felipeclopes** [comment]
The issue was happening in my end due to opening the project not the workspace in Xcode. 

It is fixed now!

**Comment by adrenaline15** [comment]
> The issue was happening in my end due to opening the project not the workspace in Xcode.
> It is fixed now!

You are absolutely right, if I'm opening the workspace in xcode I can build the project (since the pods/dependent stuff get also imported via xcodeworksapce-file) successfully; but thats not a suitable solution for me.. 

I would like to automate the building process without any necessary GUI-interaction. (aka via CLI)

**Comment by felipeclopes** [comment]
Our process is fully automated, the only steps we do have in our CI, is to make sure we have an updated enough pods gem and pods. The CI run `pod repo update` and `pod install` on the platform specific folder, before building it.

**Comment by AleCat83** [comment]
I have the same issue with version 4.1.3 and ionic 3 when building for IOS.
I can build using xcode and that is fine but I can't use ionic run with livereload because the build error kill the live reload server. This is slowing down the our development process a lot.
Can't even go back to plugin 3X due to the UIWebView and apple rejection problem (ITMS-90809). 
Is this going to be fixed in a new release or is there a workaround?
Thanks

**Comment by sysmo-dsv** [comment]
> I have the same issue with version 4.1.3 and ionic 3 when building for IOS.
> I can build using xcode and that is fine but I can't use ionic run with livereload because the build error kill the live reload server. This is slowing down the our development process a lot.
> Can't even go back to plugin 3X due to the UIWebView and apple rejection problem (ITMS-90809).
> Is this going to be fixed in a new release or is there a workaround?
> Thanks

I am facing the same problem using ionic 4. I also cannot go back to version 3.x of the plugin for the same reason as the depreciation of the UIWebView usage.  I'm waiting for a correction.

**Comment by SidiBecker** [comment]
Hello. I found a solution for this error. I'm using Ionic 4.x and Xcode 11.4.1.

I installed the following versions: 
`ionic cordova plugin add branch-cordova-sdk@4.1.3`
`npm i @ionic-native/branch-io@5.26.0`
`npm i @ionic-cli@latest`

I removed the plugins folder and reinstalled the platform:
`rm -rf plugins/`
`ionic cordova platform rm ios && ionic cordova platform add ios@5.1.1`

Before executing the build command, I did the following procedures:
- I opened the `.workspace `on `platforms/ios`;
- I opened the "Build Settings" tab;
- I searched for "Header Search Paths" and added the following paths in `debug` and `release` configuration:
`"${PODS_ROOT}/Branch/Branch-SDK/Branch-SDK"`
`"${PODS_ROOT}/Branch/Branch-SDK/Branch-SDK/Networking"`

With these procedures the build is successful and I no longer have the issue ITMS-90809 (UIWebView usage) when uploading my application. Hope this helps.

**Comment by sysmo-dsv** [comment]
> Hello. I found a solution for this error. I'm using Ionic 4.x and Xcode 11.4.1.
> 
> I removed the plugins folder:
> `rm -rf plugins/`
> 
> I installed/updated the following versions:
> `npm i @ionic-cli@latest`
> 
> `ionic cordova plugin rm branch-cordova-sdk`
> `ionic cordova plugin add branch-cordova-sdk@4.1.3`
> `npm i @ionic-native/branch-io@5.26.0`
> 
> `ionic cordova plugin rm cordova-open-native-settings`
> `ionic cordova plugin add cordova-open-native-settings@1.5.2`
> `npm i @ionic-native/open-native-settings@5.26.0`
> 
> I reinstalled the ios platform:
> `ionic cordova platform rm ios`
> `ionic cordova platform add ios@5.1.1`
> 
> Before executing the build command, I did the following procedures:
> 
> * I opened the `.xcworkspace` file on `platforms/ios/` folder;
> * I opened the "Build Settings" tab;
> * I searched for "Header Search Paths" and added the following paths in `debug` and `release` configuration:
>   `"${PODS_ROOT}/Branch/Branch-SDK/Branch-SDK"`
>   `"${PODS_ROOT}/Branch/Branch-SDK/Branch-SDK/Networking"`
> 
> With these procedures the build is successful and I no longer have the issue ITMS-90809 (UIWebView usage) when uploading my application. Hope this helps.

Works for me! Thanks!

**Comment by Sroose** [comment]
Thanks @SidiBecker !
Actually the search headers are the only thing we needed to get this working.

I've created a hook which can be added to your Ionic project which will fix (workaround) the issue by adding these 2 header search paths automatically:
https://gist.github.com/Sroose/d3db4178babbab1b39b68e9889e7869b

@ Branch team, I think this should be fixed in the Pod?

**Comment by SidiBecker** [comment]
Wonderful automation @Sroose. Thanks!

**Comment by noahcooper** [comment]
Any update from the Branch team? I'm stuck on v3.4.0 because of this issue

**Comment by jffs** [comment]
any news?

**Comment by adrianyg7** [comment]
Hey @adrenaline15 and @felipeclopes please refer to https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/604#issuecomment-558997030

I have tried to reproduce this issue with a fresh ionic install but it's building and running fine.
Branch is usually the first plugin and/or Pod. I quote the following text from the same issue linked above

> any build error in any pod will also cause it (because Branch is usually the first Pod, so it will come first alphabetically after the main project attempts to resolve Pod dependencies)

If you still have the same issue after this, please provide a minimal reproducible case.

**Comment by noahcooper** [comment]
This can be reproduced by using `branch-cordova-sdk` along with `cordova-plugin-facebook4`.

**Comment by jffs** [comment]
how we can fix it if have to use facebook plugin?

**Comment by adrianyg7** [comment]
Here is a PR that will help with this https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/pull/660 while this gets merged and released you can add the hook @Sroose shared above. (Thanks @sysmo-dsv for the contribution)

Please note that some plugins still use the old CocoaPods way to resolve config dirs or other obscure ways that modify CocoaPods config causing other plugins to fail, since Branch is usually the first pod alphabetically, it'll show up as the error when attempting to build the main project.

**Comment by noahcooper** [comment]
Branch team, any thoughts on when the fix for this will be released?

**Comment by echo-branch** [comment]
Sorry for the delay.  There's some iOS 14 related work that we'd like to include with the next release and choose to delay a bit.

**Comment by noahcooper** [comment]
Version 4.2.0 of this plugin still fails when `cordova-plugin-facebook4` is used.

**Comment by gopi-hl** [comment]
@echo-branch : We are not able to build an iOS build when we use your plugin. This is a work stoppage. Any ideas when this will get released - I am talking about the Branch.h file not found error

**Comment by mvaullerin** [comment]
We still have issues building our app with the 4.2.0 : 

```
[...]/branch-cordova-sdk/BranchSDK.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[cordova] (1 failure)
[cordova] xcodebuild: Command failed with exit code 65
```

It seems there is a conflict with cordova-plugin-googleplus: 8.5.0

**Comment by noahcooper** [comment]
Any update from the Branch team? Version 4 of this plugin has been broken for 6 months now. With upcoming iOS changes, it'll be important for all developers to move off of version 3.

**Comment by noahcooper** [comment]
Anything?

**Comment by echo-branch** [comment]
@noahcooper 
We believe the issue is plugin compatibility.

We have a potential fix on staging, which is waiting on an iOS patch release.  You could try pointing there to see if it resolves the issue.

It would be pretty helpful if you could share what other 3rd party plugins you're using.

**Comment by noahcooper** [comment]
@echo-branch I'm encountering this issue when using this plugin with the `cordova-plugin-facebook4` plugin.

**Comment by noahcooper** [comment]
Any chance of a release of this plugin sometime soon with the fix for this issue?

**Comment by echo-branch** [comment]
@noahcooper sorry about that, i totally dropped the ball on this patch release.  Getting out now.

**Comment by noahcooper** [comment]
Yay, my build is working again. Thanks, Branch team!

**Comment by tamsel12** [comment]
No it is not working for me. Still getting the same issue while build the app
