### ISSUE TITLE
Legacy ionic 3 app build problems with branch-cordova-sdk

### ISSUE THREAD

**Issue by newuser44** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#654]
Been having this problem for weeks now.  
A legacy app that is on ionic 3.  Have updated to cordova iOS 5.  Could be other programs that our outdated too? 
Been trying to get things to build with  
<plugin name="branch-cordova-sdk" spec="^4.1.3" />

Trying to do fresh set up.  

```
cordova platform add ios@5
Using cordova-fetch for cordova-ios@5
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.app-MWA-Carrier.test
	Name: CarrierControl
iOS project created with cordova-ios@5.1.1
Installing "branch-cordova-sdk" for ios
Failed to install 'branch-cordova-sdk': Error: Cannot find module 'xml2js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/sbrothers/work/appRelease/mobileapps/carrier-control/plugins/branch-cordova-sdk/src/scripts/lib/xmlHelper.js:5:18
```

Each time I try something else I get a different error.  I'll keep posting what I find. 
I think my next step is to remove branch.

**Comment by Sroose** [comment]
Same here on Ionic4

```
In file included from xxx/Plugins/branch-cordova-sdk/BranchSDK.m:1:
xxx/Plugins/branch-cordova-sdk/BranchSDK.h:4:9: fatal error: 'Branch.h' file not found
#import "Branch.h"
        ^~~~~~~~~~
1 error generated.
```

**Comment by newuser44** [comment]
Any update?  Getting the same problem and searching the web for a solution.  Google brings me back to my own problem from months ago.  

Adding platfrom iOS auto address all the plugins which seems to cause a problem for Branch io.    
Please advice?

**Comment by Sroose** [comment]
Duplicate of https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/issues/642
@newuser44 you can find my workaround there
