### ISSUE TITLE
BranchIo is not injectable

### ISSUE THREAD

**Issue by sadelbrid** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#707]
In my Ionic 6 / Angular 13 application, when I try to inject BranchIo into my app.component.ts, I get the following error:

```
NullInjectorError: R3InjectorError(D)[a -> a -> a]: 
  NullInjectorError: No provider for a!
    at hg.get (main.js:1:889901)
    at r_.get (main.js:1:891254)
    at r_.get (main.js:1:891254)
    at r_.get (main.js:1:891254)
    at Ov.get (main.js:1:918728)
    at Object.get (main.js:1:915534)
    at F (main.js:1:853346)
    at S (main.js:1:854142)
    at Object.td (main.js:1:899138)
    at D.ɵfac [as factory] (main.js:1:570688)
```

Here is my import:

`import { BranchIo } from '@awesome-cordova-plugins/branch-io/ngx';
`

And here is my injection:

```
constructor(
        private navCtrl: NavController,
        private platform: Platform,
        private splashScreen: SplashScreen,
        private statusBar: StatusBar,
        private menu: MenuController,
        private socialSharing: SocialSharing,
        private keyboard: Keyboard,
        private eventChange: EventChangeService,
        private branch: BranchService,
        private branchIo: BranchIo // <--- This fails.
){
	// stuff
}

```

I assume this is the preferred way to import Branch, because this is the example code given on [the Ionic Branch-IO page](https://ionicframework.com/docs/native/branch-io) and window.Branch doesn't exist (even though that's how [the Branch docs](https://help.branch.io/developers-hub/docs/cordova-phonegap-ionic) say to access it).

This issue is happening in iOS, Android, & Browser.

Here are relevant library versions:

```
"cordova": "^11.0.0",
"@awesome-cordova-plugins/branch-io": "^5.43.0",
"branch-cordova-sdk": "^5.1.0",
"cordova-android": "^10.1.2",
"cordova-ios": "^6.2.0",
"cordova-browser": "^5.0.4",
"@ionic/angular": "^6.1.7",
"@ionic/core": "^6.1.7"
```

I just upgraded from Ionic 5 (Angular 8) => Ionic 6 (Angular 13) and this is the final hurdle that's keeping me from being able to update my app. Please help!

**Comment by sadelbrid** [comment]
So, I wasn't adding BranchIo as a provider in my app.module.ts. All good now!
